Feat/parameterized macros
MIAOU-Polytech/BRAINF-CK_SI3 pull request #60
Opened 2016-11-30 15:26 UTC by piernov

Supersedes #56

2016-11-30 16:01 UTC, sticmac commented
Maybe `MACRO_ARGS` is not needed anymore?

2016-11-30 16:02 UTC, sticmac requested changes
Some modifications to do still, in my opinion.
(See my comments).

2016-11-30 16:02 UTC, sticmac commented on src/brainfuck/MacroParser.java
> +		return IntStream.range(0, repeat).mapToObj(i -> macro.getBody().flatMap(this::parseLine)).flatMap(t->t);
Could you put comments about this?
And write it on several lines?

2016-11-30 21:04 UTC, sticmac approved these changes

2016-12-02 14:53 UTC, piernov commented
@Tordesillas @sticmac @NassimBounouas 
Do we want to use this implementation in the end?
(if so, #58 must be reworked)

2016-12-02 23:05 UTC, sticmac commented
@piernov I can't think of any better solution, so i think this one could be great.

2016-12-06 19:42 UTC, NassimBounouas approved these changes

2016-12-07 07:13 UTC, merged